/* file: fetch_trace_probe.sv
 Description: Simulation-only fetch path trace probe.
 Author: Jeremy Cai
 Date: May 07, 2026
 Version: 1.0
*/
`ifdef SIMULATION
module fetch_trace_probe
    import rv64gc_pkg::*;
    import uarch_pkg::*;
(
    input logic                             clk,
    input logic                             rst_n,
    input logic [63:0]                      f1_pc,
    input logic                             ic_req_valid,
    input logic [63:0]                      ic_req_addr,
    input logic                             ic_resp_valid,
    input logic                             ic_resp_hit,
    input logic                             nlpb_hit_comb,
    input logic                             f2_work_valid_c,
    input logic [63:0]                      f2_work_pc_c,
    input logic                             f2_btb_hit_r,
    input logic [2:0]                       f2_btb_type_r,
    input logic [5:0]                       f2_btb_offset_r,
    input logic                             f2_btb_alt_hit_r,
    input logic [2:0]                       f2_btb_alt_type_r,
    input logic [5:0]                       f2_btb_alt_offset_r,
    input logic [2:0]                       extract_count,
    input logic [2:0]                       final_count,
    input logic                             f2_will_emit_c,
    input logic                             f2_duplicate_suppressed_c,
    input logic                             f2_seq_valid,
    input logic [63:0]                      f2_seq_next_pc,
    input logic                             f2_line_state_use_c,
    input logic                             bp_branch_found,
    input logic                             bp_taken,
    input logic [2:0]                       bp_type,
    input logic [2:0]                       bp_branch_slot,
    input logic [63:0]                      bp_target_addr,
    input logic                             predecode_ctl_found,
    input logic [2:0]                       predecode_ctl_slot,
    input logic [2:0]                       predecode_ctl_type,
    input logic [63:0]                      predecode_ctl_pc,
    input logic [63:0]                      predecode_ctl_target,
    input logic                             ftq_pred_ctl_valid,
    input logic                             ftq_pred_ctl_taken,
    input logic [2:0]                       ftq_pred_ctl_slot,
    input logic [2:0]                       ftq_pred_ctl_type,
    input logic                             pd_pred_mismatch,
    input logic                             subgroup_seed_valid_r,
    input logic [63:0]                      subgroup_seed_pc_r,
    input logic                             subgroup_seed_pred_taken_r,
    input logic [63:0]                      subgroup_seed_parent_pc_r,
    input logic [63:0]                      subgroup_seed_owner_pc_r,
    input logic [4:0]                       ras_tos,
    input logic                             ras_push_valid,
    input logic [63:0]                      ras_push_addr,
    input logic                             ras_pop_valid,
    input logic [63:0]                      ras_pop_addr,
    input logic                             f2_bpu_redirect,
    input logic [63:0]                      f2_bpu_target,
    input logic                             redirect_valid,
    input logic [63:0]                      redirect_pc,
    input logic                             remainder_valid_r,
    input logic                             consume_remainder_c,
    input logic                             consumed_remainder_r,
    input logic                             ftq_need_alloc_c,
    input logic                             ftq_enq_valid,
    input logic [FTQ_ALLOC_TAG_BITS-1:0]    ftq_enq_tag,
    input logic                             ftq_pop_valid,
    input logic [FTQ_IDX_BITS:0]            ftq_count,
    input logic                             ftq_head_valid,
    input logic [FTQ_IDX_BITS-1:0]          ftq_head_idx,
    input logic [FTQ_ALLOC_TAG_BITS-1:0]    ftq_head_tag,
    input logic                             f2_work_ftq_valid_c,
    input logic [FTQ_IDX_BITS-1:0]          f2_work_ftq_idx_c,
    input logic [FTQ_ALLOC_TAG_BITS-1:0]    f2_work_ftq_alloc_tag_c,
    input ftq_entry_t                       f2_work_ftq_entry_c,
    input logic                             packet_buf_owner_match_c,
    input logic                             packet_buf_valid,
    input fetch_packet_t                    packet_buf_head,
    input logic                             frontend_hold,
    input logic                             fe_stall,
    input logic [2:0]                       fetch_count,
    input logic                             f2_has_emit_payload_c,
    input logic                             f2_last_emit_valid_r,
    input logic [63:0]                      f2_last_emit_pc_r,
    input logic [63:0]                      f2_last_emit_next_pc_r,
    input logic                             f2_replay_block_hit_c,
    input logic [63:0]                      f2_replay_block_pc_r,
    input logic [1:0]                       f2_replay_block_age_r,
    input logic                             straddle_detected,
    input logic [63:0]                      fetch_pc [0:PIPE_WIDTH-1],
    input logic                             f2_owner_completion_candidate_c,
    input logic                             f2_ftq_owner_live_c,
    input logic                             ftq_ifu_wb_owner_valid,
    input logic [FTQ_IDX_BITS-1:0]          ftq_ifu_wb_owner_idx,
    input logic [FTQ_ALLOC_TAG_BITS-1:0]    ftq_ifu_wb_owner_tag,
    input logic                             ifu_runahead_req_fire_c,
    input logic                             ifu_runahead_cancel_next_c,
    input logic                             ifu_runahead_pending_c,
    input logic [63:0]                      ifu_runahead_pending_pc_c,
    input logic [FTQ_ALLOC_TAG_BITS-1:0]    ifu_runahead_pending_tag_c,
    input logic [FTQ_IDX_BITS:0]            ftq_count_alloc_to_ifu,
    input logic [FTQ_IDX_BITS:0]            ftq_count_ifu_to_wb,
    input logic [FTQ_IDX_BITS:0]            ftq_count_ifu_to_commit,
    input logic                             icq_deq_valid,
    input logic [63:LINE_BITS]              icq_deq_line_addr,
    input logic                             packet_buf_head_owner_complete_c,
    input logic                             subgroup_seed_load_c,
    input logic [63:0]                      subgroup_split_pc_c,
    input logic [63:0]                      subgroup_split_target_c,
    input logic [2:0]                       subgroup_split_slot_c,
    input logic [2:0]                       subgroup_split_type_c,
    input logic                             subgroup_split_seed_c,
    input logic [63:0]                      second_ctl_pc,
    input logic [63:0]                      second_ctl_target,
    input logic                             owner_cond_pred_found
);

    logic trace_fetch_en;
    logic trace_fetch_all_en;
    logic trace_fetch_split_en;
    logic trace_fetch_dup_en;
    logic trace_fetch_owner_en;
    integer trace_fetch_cycle;

    initial begin
        trace_fetch_en = 1'b0;
        trace_fetch_all_en = 1'b0;
        trace_fetch_split_en = 1'b0;
        trace_fetch_dup_en = 1'b0;
        trace_fetch_owner_en = 1'b0;
        if ($test$plusargs("TRACE_FETCH")) trace_fetch_en = 1'b1;
        if ($test$plusargs("TRACE_FETCH_ALL")) trace_fetch_all_en = 1'b1;
        if ($test$plusargs("TRACE_FETCH_SPLIT")) trace_fetch_split_en = 1'b1;
        if ($test$plusargs("FETCH_DUP_TRACE")) trace_fetch_dup_en = 1'b1;
        if ($test$plusargs("TRACE_FETCH_OWNER")) trace_fetch_owner_en = 1'b1;
    end

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            trace_fetch_cycle <= 0;
        end else begin
            trace_fetch_cycle <= trace_fetch_cycle + 1;
            if (trace_fetch_en &&
                (trace_fetch_all_en ||
                 (trace_fetch_cycle < 600) ||
                 ((f1_pc >= 64'h0000_0000_8000_2000) &&
                  (f1_pc <  64'h0000_0000_8000_2470)) ||
                 ((f1_pc >= 64'h0000_0000_8000_2500) &&
                  (f1_pc <  64'h0000_0000_8000_2560)) ||
                 ((f1_pc >= 64'h0000_0000_8000_3100) &&
                  (f1_pc <  64'h0000_0000_8000_3400)) ||
                 ((f1_pc >= 64'h0000_0000_8000_39f0) &&
                  (f1_pc <  64'h0000_0000_8000_3a80)) ||
                 ((f2_work_pc_c >= 64'h0000_0000_8000_2000) &&
                  (f2_work_pc_c <  64'h0000_0000_8000_2470)) ||
                 ((f2_work_pc_c >= 64'h0000_0000_8000_2500) &&
                  (f2_work_pc_c <  64'h0000_0000_8000_2560)) ||
                 ((f2_work_pc_c >= 64'h0000_0000_8000_3100) &&
                  (f2_work_pc_c <  64'h0000_0000_8000_3400)) ||
                 ((f2_work_pc_c >= 64'h0000_0000_8000_39f0) &&
                  (f2_work_pc_c <  64'h0000_0000_8000_3a80)))) begin
                $display("[FETCH] cyc=%0d f1_pc=%016h ic_req_v=%b ic_req=%016h ic_resp_v=%b ic_hit=%b nlpb_hit=%b f2_v=%b f2_pc=%016h f2_hit=%b f2_type=%0d f2_off=%0d f2_alt_hit=%b f2_alt_type=%0d f2_alt_off=%0d ext=%0d final=%0d emit=%b dup=%b seq_v=%b seq_pc=%016h line_reuse=%b bp=%b bp_taken=%b bp_type=%0d bp_slot=%0d bp_tgt=%016h pd_v=%b pd_slot=%0d pd_type=%0d pd_tgt=%016h ftq_pred_v=%b ftq_pred_t=%b ftq_pred_slot=%0d ftq_pred_type=%0d ftq_sub=%b pd_mm=%b sg_v=%b sg_pc=%016h sg_t=%b sg_parent=%016h sg_owner=%016h ras_tos=%0d ras_push=%b ras_push_addr=%016h ras_pop=%b ras_pop_addr=%016h redir=%b redir_pc=%016h cmt_redir=%b cmt_pc=%016h rem_v=%b cons_rem=%b consd_rem=%b ftq_need=%b ftq_enq=%b ftq_enq_tag=%0d ftq_pop=%b ftq_cnt=%0d ftq_head_v=%b ftq_head=%0d ftq_head_tag=%0d f2_ftq_v=%b f2_ftq=%0d f2_ftq_tag=%0d f2_ftq_blk=%016h ra_fire=%b ra_cancel=%b ra_pend=%b ra_pc=%016h ra_tag=%0d pkt_live=%b pkt_ftq_tag=%0d fe_hold=%b fe_stall=%b fetch_out=%0d",
                    trace_fetch_cycle,
                    f1_pc,
                    ic_req_valid,
                    ic_req_addr,
                    ic_resp_valid,
                    ic_resp_hit,
                    nlpb_hit_comb,
                    f2_work_valid_c,
                    f2_work_pc_c,
                    f2_btb_hit_r,
                    f2_btb_type_r,
                    f2_btb_offset_r,
                    f2_btb_alt_hit_r,
                    f2_btb_alt_type_r,
                    f2_btb_alt_offset_r,
                    extract_count,
                    final_count,
                    f2_will_emit_c,
                    f2_duplicate_suppressed_c,
                    f2_seq_valid,
                    f2_seq_next_pc,
                    f2_line_state_use_c,
                    bp_branch_found,
                    bp_taken,
                    bp_type,
                    bp_branch_slot,
                    bp_target_addr,
                    predecode_ctl_found,
                    predecode_ctl_slot,
                    predecode_ctl_type,
                    predecode_ctl_target,
                    ftq_pred_ctl_valid,
                    ftq_pred_ctl_taken,
                    ftq_pred_ctl_slot,
                    ftq_pred_ctl_type,
                    f2_work_ftq_entry_c.pred_from_subgroup,
                    pd_pred_mismatch,
                    subgroup_seed_valid_r,
                    subgroup_seed_pc_r,
                    subgroup_seed_pred_taken_r,
                    subgroup_seed_parent_pc_r,
                    subgroup_seed_owner_pc_r,
                    ras_tos,
                    ras_push_valid,
                    ras_push_addr,
                    ras_pop_valid,
                    ras_pop_addr,
                    f2_bpu_redirect,
                    f2_bpu_target,
                    redirect_valid,
                    redirect_pc,
                    remainder_valid_r,
                    consume_remainder_c,
                    consumed_remainder_r,
                    ftq_need_alloc_c,
                    ftq_enq_valid,
                    ftq_enq_tag,
                    ftq_pop_valid,
                    ftq_count,
                    ftq_head_valid,
                    ftq_head_idx,
                    ftq_head_tag,
                    f2_work_ftq_valid_c,
                    f2_work_ftq_idx_c,
                    f2_work_ftq_alloc_tag_c,
                    f2_work_ftq_entry_c.block_pc,
                    ifu_runahead_req_fire_c,
                    ifu_runahead_cancel_next_c,
                    ifu_runahead_pending_c,
                    ifu_runahead_pending_pc_c,
                    ifu_runahead_pending_tag_c,
                    packet_buf_owner_match_c,
                    packet_buf_valid ? packet_buf_head.ftq_alloc_tag : '0,
                    frontend_hold,
                    fe_stall,
                    fetch_count);
            end
            if (trace_fetch_dup_en &&
                f2_has_emit_payload_c &&
                !f2_will_emit_c) begin
                $display("[FETCH_DUP] cyc=%0d pc=%016h last_v=%b last_pc=%016h last_next=%016h replay_hit=%b replay_pc=%016h replay_age=%0d seq_v=%b seq=%016h ext=%0d final=%0d f2_ftq_v=%b f2_ftq=%0d f2_tag=%0d block=%016h pred_v=%b pred_t=%b pred_off=%0d pred_type=%0d pred_target=%016h pd_v=%b pd_slot=%0d pd_type=%0d pd_target=%016h bp=%b bp_taken=%b bp_slot=%0d bp_type=%0d bp_target=%016h rem_v=%b straddle=%b fe_stall=%b fe_hold=%b pkt_v=%b pkt_tag=%0d ftq_head_v=%b ftq_head=%0d ftq_head_tag=%0d ftq_cnt=%0d fetch_out=%0d out_pc0=%016h out_pc1=%016h out_pc2=%016h out_pc3=%016h",
                    trace_fetch_cycle,
                    f2_work_pc_c,
                    f2_last_emit_valid_r,
                    f2_last_emit_pc_r,
                    f2_last_emit_next_pc_r,
                    f2_replay_block_hit_c,
                    f2_replay_block_pc_r,
                    f2_replay_block_age_r,
                    f2_seq_valid,
                    f2_seq_next_pc,
                    extract_count,
                    final_count,
                    f2_work_ftq_valid_c,
                    f2_work_ftq_idx_c,
                    f2_work_ftq_alloc_tag_c,
                    f2_work_ftq_entry_c.block_pc,
                    f2_work_ftq_entry_c.pred_ctl_valid,
                    f2_work_ftq_entry_c.pred_ctl_taken,
                    f2_work_ftq_entry_c.pred_ctl_offset,
                    f2_work_ftq_entry_c.pred_ctl_type,
                    f2_work_ftq_entry_c.pred_ctl_target,
                    predecode_ctl_found,
                    predecode_ctl_slot,
                    predecode_ctl_type,
                    predecode_ctl_target,
                    bp_branch_found,
                    bp_taken,
                    bp_branch_slot,
                    bp_type,
                    bp_target_addr,
                    remainder_valid_r,
                    straddle_detected,
                    fe_stall,
                    frontend_hold,
                    packet_buf_valid,
                    packet_buf_valid ? packet_buf_head.ftq_alloc_tag : '0,
                    ftq_head_valid,
                    ftq_head_idx,
                    ftq_head_tag,
                    ftq_count,
                    fetch_count,
                    fetch_pc[0],
                    fetch_pc[1],
                    fetch_pc[2],
                    fetch_pc[3]);
            end
            if (trace_fetch_owner_en &&
                f2_owner_completion_candidate_c &&
                !f2_ftq_owner_live_c) begin
                $display("[FETCH_OWNER_TRACE] cyc=%0d pc=%016h seq=%016h final=%0d straddle=%b bp=%b bp_taken=%b bp_slot=%0d bp_type=%0d target=%016h work_idx=%0d work_tag=%0d wb_valid=%b wb_idx=%0d wb_tag=%0d ftq_cnt=%0d ftq_alloc_to_ifu=%0d ftq_ifu_to_wb=%0d ftq_ifu_to_commit=%0d icq_valid=%b icq_line=%014h line_reuse=%b pkt_valid=%b pkt_match=%b pkt_complete=%b fetch_out=%0d out_pc0=%016h",
                    trace_fetch_cycle,
                    f2_work_pc_c,
                    f2_seq_next_pc,
                    final_count,
                    straddle_detected,
                    bp_branch_found,
                    bp_taken,
                    bp_branch_slot,
                    bp_type,
                    bp_target_addr,
                    f2_work_ftq_idx_c,
                    f2_work_ftq_alloc_tag_c,
                    ftq_ifu_wb_owner_valid,
                    ftq_ifu_wb_owner_idx,
                    ftq_ifu_wb_owner_tag,
                    ftq_count,
                    ftq_count_alloc_to_ifu,
                    ftq_count_ifu_to_wb,
                    ftq_count_ifu_to_commit,
                    icq_deq_valid,
                    icq_deq_line_addr,
                    f2_line_state_use_c,
                    packet_buf_valid,
                    packet_buf_owner_match_c,
                    packet_buf_head_owner_complete_c,
                    fetch_count,
                    fetch_pc[0]);
            end
            if (trace_fetch_split_en && subgroup_seed_load_c) begin
                $display("[FETCH_SPLIT] cyc=%0d parent_pc=%016h split_pc=%016h split_tgt=%016h split_slot=%0d split_type=%0d reason=%s pre_pc=%016h pre_tgt=%016h second_pc=%016h second_tgt=%016h ftq_pred_v=%b ftq_pred_t=%b ftq_pred_slot=%0d ftq_pred_type=%0d owner_pred=%b bp_found=%b bp_taken=%b bp_slot=%0d final=%0d ext=%0d",
                    trace_fetch_cycle,
                    f2_work_pc_c,
                    subgroup_split_pc_c,
                    subgroup_split_target_c,
                    subgroup_split_slot_c,
                    subgroup_split_type_c,
                    subgroup_split_seed_c ? "owner" : "second",
                    predecode_ctl_pc,
                    predecode_ctl_target,
                    second_ctl_pc,
                    second_ctl_target,
                    ftq_pred_ctl_valid,
                    ftq_pred_ctl_taken,
                    ftq_pred_ctl_slot,
                    ftq_pred_ctl_type,
                    owner_cond_pred_found,
                    bp_branch_found,
                    bp_taken,
                    bp_branch_slot,
                    final_count,
                    extract_count);
            end
        end
    end

endmodule

bind fetch_top fetch_trace_probe u_fetch_trace_probe (
    .clk                             (clk),
    .rst_n                           (rst_n),
    .f1_pc                           (f1_pc),
    .ic_req_valid                    (ic_req_valid),
    .ic_req_addr                     (ic_req_addr),
    .ic_resp_valid                   (ic_resp_valid),
    .ic_resp_hit                     (ic_resp_hit),
    .nlpb_hit_comb                   (nlpb_hit_comb),
    .f2_work_valid_c                 (f2_work_valid_c),
    .f2_work_pc_c                    (f2_work_pc_c),
    .f2_btb_hit_r                    (f2_btb_hit_r),
    .f2_btb_type_r                   (f2_btb_type_r),
    .f2_btb_offset_r                 (f2_btb_offset_r),
    .f2_btb_alt_hit_r                (f2_btb_alt_hit_r),
    .f2_btb_alt_type_r               (f2_btb_alt_type_r),
    .f2_btb_alt_offset_r             (f2_btb_alt_offset_r),
    .extract_count                   (extract_count),
    .final_count                     (final_count),
    .f2_will_emit_c                  (f2_will_emit_c),
    .f2_duplicate_suppressed_c       (f2_duplicate_suppressed_c),
    .f2_seq_valid                    (f2_seq_valid),
    .f2_seq_next_pc                  (f2_seq_next_pc),
    .f2_line_state_use_c             (f2_line_state_use_c),
    .bp_branch_found                 (bp_branch_found),
    .bp_taken                        (bp_taken),
    .bp_type                         (bp_type),
    .bp_branch_slot                  (bp_branch_slot),
    .bp_target_addr                  (bp_target_addr),
    .predecode_ctl_found             (predecode_ctl_found),
    .predecode_ctl_slot              (predecode_ctl_slot),
    .predecode_ctl_type              (predecode_ctl_type),
    .predecode_ctl_pc                (predecode_ctl_pc),
    .predecode_ctl_target            (predecode_ctl_target),
    .ftq_pred_ctl_valid              (ftq_pred_ctl_valid),
    .ftq_pred_ctl_taken              (ftq_pred_ctl_taken),
    .ftq_pred_ctl_slot               (ftq_pred_ctl_slot),
    .ftq_pred_ctl_type               (ftq_pred_ctl_type),
    .pd_pred_mismatch                (pd_pred_mismatch),
    .subgroup_seed_valid_r           (subgroup_seed_valid_r),
    .subgroup_seed_pc_r              (subgroup_seed_pc_r),
    .subgroup_seed_pred_taken_r      (subgroup_seed_pred_taken_r),
    .subgroup_seed_parent_pc_r       (subgroup_seed_parent_pc_r),
    .subgroup_seed_owner_pc_r        (subgroup_seed_owner_pc_r),
    .ras_tos                         (ras_tos),
    .ras_push_valid                  (ras_push_valid),
    .ras_push_addr                   (ras_push_addr),
    .ras_pop_valid                   (ras_pop_valid),
    .ras_pop_addr                    (ras_pop_addr),
    .f2_bpu_redirect                 (f2_bpu_redirect),
    .f2_bpu_target                   (f2_bpu_target),
    .redirect_valid                  (redirect_valid),
    .redirect_pc                     (redirect_pc),
    .remainder_valid_r               (remainder_valid_r),
    .consume_remainder_c             (consume_remainder_c),
    .consumed_remainder_r            (consumed_remainder_r),
    .ftq_need_alloc_c                (ftq_need_alloc_c),
    .ftq_enq_valid                   (ftq_enq_valid),
    .ftq_enq_tag                     (ftq_enq_tag),
    .ftq_pop_valid                   (ftq_ifu_pop_valid),
    .ftq_count                       (ftq_count),
    .ftq_head_valid                  (ftq_head_valid),
    .ftq_head_idx                    (ftq_head_idx),
    .ftq_head_tag                    (ftq_head_tag),
    .f2_work_ftq_valid_c             (f2_work_ftq_valid_c),
    .f2_work_ftq_idx_c               (f2_work_ftq_idx_c),
    .f2_work_ftq_alloc_tag_c         (f2_work_ftq_alloc_tag_c),
    .f2_work_ftq_entry_c             (f2_work_ftq_entry_c),
    .packet_buf_owner_match_c        (packet_buf_owner_match_c),
    .packet_buf_valid                (packet_buf_valid),
    .packet_buf_head                 (packet_buf_head),
    .frontend_hold                   (frontend_hold),
    .fe_stall                        (fe_stall),
    .fetch_count                     (fetch_count),
    .f2_has_emit_payload_c           (f2_has_emit_payload_c),
    .f2_last_emit_valid_r            (f2_last_emit_valid_r),
    .f2_last_emit_pc_r               (f2_last_emit_pc_r),
    .f2_last_emit_next_pc_r          (f2_last_emit_next_pc_r),
    .f2_replay_block_hit_c           (f2_replay_block_hit_c),
    .f2_replay_block_pc_r            (f2_replay_block_pc_r),
    .f2_replay_block_age_r           (f2_replay_block_age_r),
    .straddle_detected               (straddle_detected),
    .fetch_pc                        (fetch_pc),
    .f2_owner_completion_candidate_c (f2_owner_completion_candidate_c),
    .f2_ftq_owner_live_c             (f2_ftq_owner_live_c),
    .ftq_ifu_wb_owner_valid          (ftq_ifu_wb_owner_valid),
    .ftq_ifu_wb_owner_idx            (ftq_ifu_wb_owner_idx),
    .ftq_ifu_wb_owner_tag            (ftq_ifu_wb_owner_tag),
    .ifu_runahead_req_fire_c         (ifu_runahead_req_fire_c),
    .ifu_runahead_cancel_next_c      (ifu_runahead_cancel_next_c),
    .ifu_runahead_pending_c          (ifu_runahead_pending_c),
    .ifu_runahead_pending_pc_c       (ifu_runahead_pending_pc_c),
    .ifu_runahead_pending_tag_c      (ifu_runahead_pending_tag_c),
    .ftq_count_alloc_to_ifu          (ftq_count_alloc_to_ifu),
    .ftq_count_ifu_to_wb             (ftq_count_ifu_to_wb),
    .ftq_count_ifu_to_commit         (ftq_count_ifu_to_commit),
    .icq_deq_valid                   (icq_deq_valid),
    .icq_deq_line_addr               (icq_deq_line_addr),
    .packet_buf_head_owner_complete_c(packet_buf_head_owner_complete_c),
    .subgroup_seed_load_c            (subgroup_seed_load_c),
    .subgroup_split_pc_c             (subgroup_split_pc_c),
    .subgroup_split_target_c         (subgroup_split_target_c),
    .subgroup_split_slot_c           (subgroup_split_slot_c),
    .subgroup_split_type_c           (subgroup_split_type_c),
    .subgroup_split_seed_c           (subgroup_split_seed_c),
    .second_ctl_pc                   (second_ctl_pc),
    .second_ctl_target               (second_ctl_target),
    .owner_cond_pred_found           (owner_cond_pred_found)
);
`endif
